PA-5948 : Updated host generator to use aarch64 for amazon linux
voxpupuli/beaker-hostgenerator pull request #345
Opened 2023-11-17 11:52 UTC by span786

Updated data.rb in host-generator to use 'aarch64' like it is using everywhere in project

2023-11-17 18:53 UTC, mhashizume approved these changes

2023-11-17 22:33 UTC, mhashizume requested changes
Sorry, I think we need one more change here. The goal is to have BHG generate a `platform` that is appropriate for our Vanagon projects, but a `template` that is appropriate for ABS/VMPooler. Right now, your PR generates this:

```
bundle exec beaker-hostgenerator amazon2023-AARCH64a --hypervisor abs
---
HOSTS:
  amazon2023-AARCH64-1:
    platform: amazon-2023-aarch64
    hypervisor: abs
    template: amazon-2023-aarch64
    roles:
    - agent
CONFIG: {}
```

For our CI, we need the `template` to match what's in ABS/VMPooler, which is `amazon-2023-arm64`.

In addition to what you already have here, we need to move Amazon to this regex line: https://github.com/voxpupuli/beaker-hostgenerator/blob/64f315292da95440a025223a47b57d767cdd7f0f/lib/beaker-hostgenerator/hypervisor/abs.rb#L30

So we get this desired result:

```
bundle exec beaker-hostgenerator amazon2023-AARCH64a --hypervisor abs
---
HOSTS:
  amazon2023-AARCH64-1:
    platform: amazon-2023-aarch64
    hypervisor: abs
    template: amazon-2023-arm64
    roles:
    - agent
CONFIG: {}
```

2023-11-20 17:39 UTC, mhashizume approved these changes

2023-11-20 17:41 UTC, mhashizume commented
LGTM, I'm not sure what we need to do to make Codecov happy

2023-11-20 18:14 UTC, bastelfreak commented
@mhashizume just ignore it :)

2023-11-20 18:14 UTC, merged