Switch Fedora docker images to use quay.io
voxpupuli/beaker-hostgenerator pull request #391
Opened 2024-12-10 13:16 UTC by jay7x

This should unbreak Fedora on aarch64.

2024-12-10 13:52 UTC, ekohl requested changes
I'm not sure this is the best way. I'm still not a fan of the `amd64/` prefix. 209336f52bf76fd103f86793c2b122d1884e580e explains it's specifically to run the x86_64 build on ARM chips like Apple.

This already gave issues for OpenSUSE (49526d17ee255760182669535ffa6ae3004e3721) so I wonder how we should deal with architectures.

If you want to use aarch64, I think you should use `fedora40-arm64` and not `fedora40-64`.

2024-12-10 13:52 UTC, ekohl commented on lib/beaker-hostgenerator/hypervisor/docker.rb
> +        when /^(fedora)/
```suggestion
        when /^fedora/
```

2024-12-10 13:52 UTC, ekohl commented on lib/beaker-hostgenerator/data.rb
> -      (19..41).each do |release|
As noted on IRC, there are official builds that still look maintained on Fedora 36.

2024-12-12 05:41 UTC, jay7x commented
Just realized I can override the `image` field in the setfile, so this change is not required for me right now. There is larger discussion might needed wrt the way we use the architecture.

2024-12-12 05:41 UTC, closed without merging